import os
from flask import Flask, request, render_template_string, send_file, redirect, url_for
from fpdf import FPDF
import io
import stripe
import uuid

app = Flask(__name__)

# קבלת מפתחות מהשרת
app.secret_key = os.environ.get('FLASK_SECRET_KEY', 'fallback_secret_key_for_dev')
stripe.api_key = os.environ.get('STRIPE_API_KEY')

reports = {}

# --- לוגיקה וניתוח משפטי ---
def analyze_risk(project_name, data_type, target_market, risk_desc):
    desc_lower = risk_desc.lower()
    market_lower = target_market.lower()
    
    if any(x in desc_lower for x in ['social scoring', 'manipulative', 'subliminal']):
        risk_level = "UNACCEPTABLE RISK (Prohibited)"
        recommendations = "CRITICAL: Strictly forbidden under EU AI Act Article 5."
    elif any(x in desc_lower for x in ['biometric', 'surveillance']) or \
         any(x in market_lower for x in ['critical infrastructure', 'law enforcement', 'hr']):
        risk_level = "HIGH RISK"
        recommendations = "High Risk Classification. Requires conformity assessment and registration."
    elif any(x in desc_lower for x in ['chatbot', 'deepfake']):
        risk_level = "LIMITED RISK"
        recommendations = "Transparency obligations apply (Art. 50). Disclose AI usage."
    else:
        risk_level = "MINIMAL RISK"
        recommendations = "General GDPR applies. No specific AI Act obligations."
    return risk_level, recommendations

def generate_pdf(project_name, data_type, target_market, risk_desc, risk_level, recommendations):
    pdf = FPDF()
    pdf.add_page()
    
    # ניסיון לטעון לוגו
    try:
        pdf.image('logo.png', x=10, y=8, w=40)
    except:
        pass

    pdf.set_font("Arial", "B", 20)
    pdf.set_text_color(180, 0, 0)
    pdf.cell(0, 15, "KHAOS X", ln=True, align="C")
    
    pdf.set_font("Arial", "B", 14)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 10, "COMPLIANCE AUDIT REPORT", ln=True, align="C")
    pdf.line(10, 35, 200, 35)
    pdf.ln(15)
    
    pdf.set_font("Arial", "", 12)
    pdf.cell(0, 10, f"Project: {project_name}", ln=True)
    pdf.cell(0, 10, f"Market: {target_market}", ln=True)
    pdf.ln(5)
    
    pdf.set_font("Arial", "B", 14)
    pdf.cell(0, 10, f"Result: {risk_level}", ln=True)
    pdf.set_font("Arial", "", 12)
    pdf.multi_cell(0, 10, f"Recs: {recommendations}")
    
    pdf.set_y(-30)
    pdf.set_font("Arial", "I", 8)
    pdf.cell(0, 10, "Generated by Khaos X Compliance Engine. Not legal advice.", 0, 0, "C")
    
    pdf_output = io.BytesIO()
    pdf_output.write(pdf.output(dest='S').encode('latin1'))
    pdf_output.seek(0)
    return pdf_output

# --- דף הנחיתה והסליקה ---
@app.route('/', methods=['GET'])
def index():
    html = '''
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Khaos X | AI Auditor</title>
        <style>
            body { background-color: #0f1115; color: #e0e0e0; font-family: sans-serif; display: flex; justify-content: center; align-items: center; min-height: 100vh; margin: 0; }
            .container { background-color: #1a1d24; padding: 40px; border-radius: 8px; border: 1px solid #333; width: 100%; max-width: 500px; }
            h1 { text-align: center; color: #ff3b3b; margin-bottom: 10px; }
            p.desc { text-align: center; font-size: 0.9em; color: #aaa; margin-bottom: 30px; line-height: 1.4; }
            input, textarea { width: 100%; padding: 12px; margin-bottom: 20px; background: #0f1115; border: 1px solid #333; color: white; box-sizing: border-box;}
            button { width: 100%; padding: 15px; background: #b30000; color: white; border: none; font-weight: bold; cursor: pointer; }
            button:hover { background: #ff3b3b; }
        </style>
    </head>
    <body>
        <div class="container">
            <h1>Khaos X AUDITOR</h1>
            <p class="desc">Secure your innovation. Instant EU AI Act compliance reports generated by legal-tech intelligence. Avoid fines, lead with certainty.</p>
            <form action="/create-checkout-session" method="post">
                <input type="text" name="project_name" placeholder="Project Name" required>
                <input type="text" name="data_type" placeholder="Data Type" required>
                <input type="text" name="target_market" placeholder="Target Market" required>
                <textarea name="risk_desc" rows="4" placeholder="System Description..." required></textarea>
                <button type="submit">AUDIT NOW ($497)</button>
            </form>
        </div>
    </body>
    </html>
    '''
    return render_template_string(html)

@app.route('/create-checkout-session', methods=['POST'])
def create_checkout_session():
    if not stripe.api_key:
        # מצב חירום ללא סליקה - עוקף תשלום לבדיקה בלבד
        data = {
            'project_name': request.form['project_name'],
            'data_type': request.form['data_type'],
            'target_market': request.form['target_market'],
            'risk_desc': request.form['risk_desc']
        }
        risk, recs = analyze_risk(data['project_name'], data['data_type'], data['target_market'], data['risk_desc'])
        pdf = generate_pdf(data['project_name'], data['data_type'], data['target_market'], data['risk_desc'], risk, recs)
        return send_file(pdf, as_attachment=True, download_name='KhaosX_Report.pdf', mimetype='application/pdf')

    data = {
        'project_name': request.form['project_name'],
        'data_type': request.form['data_type'],
        'target_market': request.form['target_market'],
        'risk_desc': request.form['risk_desc']
    }
    report_id = str(uuid.uuid4())
    reports[report_id] = data
    
    try:
        checkout_session = stripe.checkout.Session.create(
            payment_method_types=['card'],
            line_items=[{'price_data': {'currency': 'usd', 'product_data': {'name': 'AI Act Audit'}, 'unit_amount': 49700}, 'quantity': 1}],
            mode='payment',
            success_url=url_for('success', _external=True) + '?session_id={CHECKOUT_SESSION_ID}',
            cancel_url=url_for('index', _external=True),
            metadata={'report_id': report_id}
        )
        return redirect(checkout_session.url, code=303)
    except Exception as e:
        return f"Stripe Error: {str(e)}"

@app.route('/success')
def success():
    session_id = request.args.get('session_id')
    checkout_session = stripe.checkout.Session.retrieve(session_id)
    report_id = checkout_session.metadata.get('report_id')
    
    if report_id in reports:
        d = reports[report_id]
        risk, recs = analyze_risk(d['project_name'], d['data_type'], d['target_market'], d['risk_desc'])
        pdf = generate_pdf(d['project_name'], d['data_type'], d['target_market'], d['risk_desc'], risk, recs)
        return send_file(pdf, as_attachment=True, download_name='KhaosX_Report.pdf', mimetype='application/pdf')
    return redirect(url_for('index'))

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5000)
